version: '3.8'

services:
  prometheus:
    build: ./prometheus
    ports:
        - 9090:9090

  grafana:
     build: ./grafana
     ports:
        - 3000:3000

  app:
    build: .
    ports:
        - 5001:80
