version: '3.8'

services:
  prometheus:
    build: ./prometheus
    ports:
        - 9090:9090

  grafana:
     build: ./grafana
     ports:
        - 3000:3000

  app:
    build: .
    ports:
        - 5001:80

  seq:
    image: datalust/seq:latest
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:5341
      - 8082:80
    volumes:
        - seqdata:/data

  db:
      image: "mcr.microsoft.com/mssql/server"
      environment:
          SA_PASSWORD: "Your_password123"
          ACCEPT_EULA: "Y"

volumes:
  seqdata: